package com.ptcrys.fpsmatch.core.minimap.format;

public enum MinimapValidationCode {
    HARD_LIMIT_EXCEEDED,
    SELF_MANIFEST_ENTRY,
    DUPLICATE_ENTRY_PATH,
    DUPLICATE_REGION_ID,
    DUPLICATE_CONNECTION_ID,
    DUPLICATE_STYLE_ID,
    DUPLICATE_FLOOR_ID,
    DUPLICATE_LAYER_ID,
    SAME_PRIORITY_FLOOR_OVERLAP,
    LAYER_ORDER_SCOPE_MISMATCH,
    LAYER_ORDER_DUPLICATE,
    LAYER_ORDER_NOT_PERMUTATION,
    BOUNDS_OUTSIDE_CANVAS,
    CONTROL_POINT_OUTSIDE_WORLD,
    CONTROL_POINT_OUTSIDE_CANVAS,
    GEOMETRY_OUTSIDE_CANVAS,
    MISSING_FLOOR_REFERENCE,
    MISSING_STYLE_REFERENCE,
    MISSING_STYLE_APPEARANCE,
    STYLE_TYPE_MISMATCH,
    MISSING_REGION_REFERENCE,
    REGION_LAYER_FLOOR_MISMATCH,
    CALIBRATION_INVALID,
    CALIBRATION_RESIDUAL_EXCEEDED
}
