plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    alias libs.plugins.modDevGradleLegacy
    alias libs.plugins.kotlinDevGradleLegacy
    alias libs.plugins.lombokLegacy
    alias libs.plugins.kotlinLombokLegacy
    alias libs.plugins.spotless
}

allprojects {
    group = 'net.ptcrys'
}

// Project identity
group = mod_group_id
version = "${minecraft_version}-${mod_version}-${file_version}"
def isRelease = file_version != "forge-snapshot"

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}

sourceSets.main.resources { srcDir 'src/generated/resources' }
sourceSets.main.kotlin { srcDir("src/main/java") }

apply from: "$projectDir/gradle/scripts/moddevgradle.gradle"
apply from: "$projectDir/dependencies.gradle"
apply from: "$projectDir/gradle/scripts/resources.gradle"
apply from: "$projectDir/gradle/scripts/jars.gradle"
apply from: "$projectDir/gradle/scripts/repositories.gradle"
apply from: "$projectDir/gradle/scripts/spotless.gradle"

generateModMetadata.doFirst {
    mkdir('run/client')
    mkdir('run/server')
    mkdir('run/clientData')
    mkdir('run/serverTest')
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
    options.compilerArgs << "-Xlint:-deprecation" << "-Xlint:-removal"
}

configurations {
    libraries
    api.extendsFrom libraries

    localImplementation
    runtimeClasspath.extendsFrom localImplementation
    compileOnly.extendsFrom localImplementation
}

jar{
    exclude "**/.cache"
    exclude "**/SimplifiedToTraditional.properties"
}

// Maven publication
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        if (isRelease) {
            maven {
                name = "PtcrysReleases"
                url = uri("https://maven.ptcrys.net/releases")
                credentials {
                    username = project.findProperty('ptcrysUsername')
                    password = project.findProperty('ptcrysPassword')
                }
            }
        } else {
            maven {
                name = "PtcrysSnapshots"
                url = uri("https://maven.ptcrys.net/snapshots")
                credentials {
                    username = project.findProperty('ptcrysUsername')
                    password = project.findProperty('ptcrysPassword')
                }
            }
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
