# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
#org.gradle.jvmargs=
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

# Minecraft / Forge / mappings
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47.4.10,)
loader_version_range=[47,)
mapping_mc_version=1.20.1
mapping_version=2023.09.03

# Required libraries and mods
ldlib2_version_range=[2.2.27+1.20.1]
modernui_version=3.12.0
tacz_version=1.1.7-hotfix
tacztweak_version=2.11.2
lrtactical_version=0.4.3
cloth_config_version=11.1.136+forge
cs_grenade_version=1.20.1-1.5.2
kotlin_forge_version=4.11.0
kubejs_version=2001.6.5-build.14
rhino_version=2001.2.3-build.6
architectury_version=9.2.14

# Build-only libraries
mixinextras_version=0.5.3
mixin_processor_version=0.8.5
json_canonicalization_version=1.1
spigot_api_version=1.20.1-R0.1-SNAPSHOT
jetbrains_annotations_version=24.0.1
mohistdev_version=1.20.1
commons_math_version=3.6.1

# Mod metadata
mod_id=fpsmatch
mod_name=FPSMatch
mod_license=GPL-3.0
mod_version=1.3.0
file_version=forge-snapshot
mod_group_id=com.ptcrys
mod_authors=SSOrangeCATY
mod_description=Git: https://github.com/SSOrangeCATY/FPSMatch\nFPS Match QQ Group: 771884981
