modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
logoFile = "icon.png"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies."${mod_id}"]]
   modId="neoforge"
   mandatory=true
   versionRange="[26.2.0.0-beta,)"
   ordering="NONE"
   side="BOTH"

[[dependencies."${mod_id}"]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies."${mod_id}"]]
  modId="tacz"
  mandatory=false
  versionRange="[1.1.4,)"
  ordering="NONE"
  side="BOTH"